import { Foods } from "./app/shared/models/food";
import { Tag } from "./app/shared/models/tag";

export const Menu:Foods[]=[
    {
        id:' 1',
        name: 'Crispy Box',
        description: '2 Pc Hot & Crispy Chicken, 1 Regular Fries, 1 Regular Drink & 1 Coleslaw.',
        price: 2.68,
        favorite: false,
        origins: ['italy','US','Pakistan','India'],
        rating: 2,
        imageUrl: 'assets/images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:' 2',
        name: 'Boneless Box',
        description: '4 Zinger Strips + 1 Coleslaw + Fries + Drink + 1 Dip + 1 Dinner Roll.',
        price: 2.92,
        favorite: false,
        rating: 4.7,
        tags: ['FastFood', 'pizza'],
        imageUrl: 'assets/images/food-2.jpg',
        origins: ['US','Pakistan','India'],
      },
      {
        id:' 3',
        name: 'Wow Box',
        description: '1 Zinger Burger + 1 Pc Chicken + 1 Fries + 1 Drink + 1 Coleslaw.',
        price: 4.20,
        favorite: false,
        rating: 2.5,
        tags: ['FastFood', 'Zinger Burger','Meal'],
        imageUrl: 'assets/images/food-3.jpg',
        origins: ['US','Pakistan'],
      },
      {
        id:' 4',
        name: 'Rice and Spice',
        description: "Aromatic arabian rice with 6 pcs of hot shot with KFC's famous vietnamese sauce",
        price: 1.46,
        favorite: true,
        rating: 4.2,
        tags: ['FastFood', 'Fries'],
        imageUrl: 'assets/images/food-4.jpg',
        origins: ['US','Pakistan','India','China'],
      },
      {
        id:'5',
        name: 'Zingeratha',
        price: 1.46,
        description: 'Crispy zinger strips rolled into a paratha with a fusion of imli ki chatni & mint mayo along with fresh onions.',
        favorite: false,
        origins: ['US'],
        rating: 4.0,
        imageUrl: 'assets/images/food-8.jpg',
        tags: ['FastFood', 'Lunch', 'Zinger'],
      },
      {
        id:'6',
        name: 'Krunch Combo',
        price: 2.03,
        description: 'Krunch burger with regular fries & regular drink.',
        favorite: false,
        origins: ['US','Pakistan','India'],
        rating: 4.0,
        imageUrl: 'assets/images/food-6.jpg',
        tags: ['FastFood', 'Zinger', 'Lunch'],
      },
      {
        id:'7',
        name: '3 Pcs Chicken',
        price: 2.36,
        description: '3 pieces of hot & crispy chicken.',
        favorite: false,
        origins: ['Pakistan'],
        rating: 4.0,
        imageUrl: 'assets/images/food-7.jpg',
        tags: ['FastFood', 'chicken', 'Lunch'],
      },
      {
        id:' 8',
        name: 'Mighty Zinger ',
        description: "2 whole muscle zingers with KFC's spicy mayo, cheese and fresh lettuce, all bundled in a Mighty bun.",
        price: 3.22,
        favorite: false,
        rating: 5,
        tags: ['FastFood', 'Zinger', 'Mighty Zinger', 'Meal'],
        imageUrl: 'assets/images/food-5.jpg',
        origins: ['Naruto','Japan','China','Korea'],
      },
] 

export const sample_tags:Tag[] = [
  { name: 'All', count: 8 },
  { name: 'FastFood', count: 8 },
  { name: 'Lunch', count: 4 },
  { name: 'Zinger', count: 3},
  { name: 'Meal', count: 2 },
  { name: 'Pcs Chicken', count: 1 },
]